### ISSUE TITLE
Loot timers window disappears when zoning into a raid

### ISSUE THREAD

**Issue by Jakobud** [papa-smurf/Gargul#71] opened 2022-11-23 21:10 UTC
I was in Naxx last night doing master looter. I have the Loot Trade Timers window (Is that what it's called?) on the screen that shows the remaining loot in my bags and the expiration timers.

When we moved to Eye of Eternity and zoned in, that loot timers window disappeared. I could not figure out how to bring it back. What is the slash command for it?

The only way I could figure out how to open it again was to open the Gargul settings > Loot trade timers > click the Demo button > click the Demo button again (it says Stop at this point) then the window was back up with the loot still there.

So I guess the bug is that the window disappears when zoning into a raid and also I have no clue how to bring up that window again in the case I had to manually.

**Comment by papa-smurf** [comment] 2022-11-23 21:20
Hi, I need to know what version you were running when this issue occurred.

As for how to do it manually: move an item around in your bag :)

**Comment by Jakobud** [comment] 2022-11-23 21:22
There is not a slash command to bring up the window? Seems like there are slash commands for all the windows.

**Comment by papa-smurf** [comment] 2022-11-23 21:25
No, that's because it pops up based on settings, unlike other windows. Also: it would be great if you could answer the question

**Comment by Jakobud** [comment] 2022-11-23 21:37
Oh ya sorry it is v4.12.11

**Comment by papa-smurf** [comment] 2022-11-23 21:42
That's impossible, since 4.12.11 was released only a couple hours ago so it must've been updated in the meantime :)

The issue with loot timers you describe was fixed in 4.12.9, which was released on 19-11-2022 (4 days ago)

Just to make sure that this wasn't caused by an outdated version please check it for one more raid and come back to me via this issue if it persists!

If it does occur again you can, as mentioned, just move around 1 item in your bag and they should pop right back up.

Cheers

**Comment by Jakobud** [comment] 2022-11-25 19:19
Ah yes it looks like it did auto update without me noticing. I will try it again in our next raid. Thanks!

**Closed** 2023-02-01 17:07 UTC
