### ISSUE TITLE
Badges of Justice Showing Up in Output

### ISSUE THREAD

**Issue by Gogo1951** [papa-smurf/Gargul#57] opened 2022-09-09 03:15 UTC
![image](https://user-images.githubusercontent.com/55365231/189264718-afc69200-4390-4efd-bf2a-a2f5b8c24954.png)

**Comment by papa-smurf** [comment] 2022-09-09 07:37
Did badge of justice get a new item ID?

This should either always happen or never happen, or maybe you were testing tmb a bit or something?

![image](https://user-images.githubusercontent.com/4224975/189297368-0d6559d6-fa3c-4763-9ee4-bcd33ff2f048.png)

**Comment by Gogo1951** [comment] 2022-09-13 06:39
Yeah it's a Currency now. Not sure how that works with Item IDs... I suspect it no longer has one.

**Comment by papa-smurf** [comment] 2022-09-13 12:00
Can't reproduce, not in heroic, not in raids, not by me, not by guildies. Clear soft-reserve (/gl sr) and TMB data (/gl tmb) and see if you can still reproduce it on >= v4.7.1

**Comment by papa-smurf** [comment] 2022-09-13 20:14
Success, could reproduce it now. Will have a looksie

**Comment by papa-smurf** [comment] 2022-09-13 20:49
This is hilarious... the game now reports item ID 42 for the badges

https://tbc.wowhead.com/item=42/oldsquires-belt

**Comment by Gogo1951** [comment] 2022-09-13 23:40
Lotta fucked up data right now. So much.

**Comment by papa-smurf** [comment] 2022-09-14 09:24
Fixed in tonight's release

**Closed by papa-smurf** 2022-09-14 09:24 UTC
